version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@3.4.2
jobs:
  development:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: which branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: The GitHub username of the user who triggered the build.
          command: echo ${CIRCLE_USERNAME}
      - add_ssh_keys:
          fingerprints:
            - "3c:ad:70:5c:87:c7:65:e4:69:47:94:88:75:a2:e3:09"
      - run:
          name: reset code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$RESET"
      - run:
          name: pull code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$PULL_DEV"
      - run:
          name: install
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$INSTALL"
      - run:
          name: install FrontEnd
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$INSTALL_FE"
      - run:
          name: build frontend
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$BUILD_FE"
      - run:
          name: reload
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "$RELOAD"
      - slack/notify:
          color: "#42e2f4"
          message: Sukses melakukan deploy pada branch $CIRCLE_BRANCH
      - slack/status:
          fail_only: true

  test-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install k6 loadimpact
          command: |
            sudo apt-get install apt-transport-https -y
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
            echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install k6
      - run:
          name: testing host
          command: k6 run dev_script.js
      - slack/notify:
          color: "#42e2f4"
          message: Sukses testing https://dev-inv.member.co.id
      - slack/status:
          fail_only: true

  staging:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: which branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: The GitHub username of the user who triggered the build.
          command: echo ${CIRCLE_USERNAME}
      - add_ssh_keys:
          fingerprints:
            - "3c:ad:70:5c:87:c7:65:e4:69:47:94:88:75:a2:e3:09"
      - run:
          name: reset code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$RESET"
      - run:
          name: pull code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$PULL_STAG"
      - run:
          name: install
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$INSTALL"
      - run:
          name: install FrontEnd
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$INSTALL_FE"
      - run:
          name: build frontend
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$BUILD_FE"
      - run:
          name: reload
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_STAG "$RELOAD"
      - slack/notify:
          color: "#42e2f4"
          message: Sukses melakukan deploy pada branch $CIRCLE_BRANCH
      - slack/status:
          fail_only: true

  test-stag:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install k6 loadimpact
          command: |
            sudo apt-get install apt-transport-https -y
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
            echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install k6
      - run:
          name: testing host
          command: k6 run stag_script.js
      - slack/notify:
          color: "#42e2f4"
          message: Sukses testing https://stg-inv.member.co.id
      - slack/status:
          fail_only: true

  production:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: which branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: The GitHub username of the user who triggered the build.
          command: echo ${CIRCLE_USERNAME}
      - add_ssh_keys:
          fingerprints:
            - "3c:ad:70:5c:87:c7:65:e4:69:47:94:88:75:a2:e3:09"
      - run:
          name: reset code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$RESET"
      - run:
          name: pull code
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$PULL_PROD"
      - run:
          name: install
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$INSTALL"
      - run:
          name: install FrontEnd
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$INSTALL_FE"
      - run:
          name: build frontend
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$BUILD_FE"
      - run:
          name: reload
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_PROD "$RELOAD"
      - slack/notify:
          color: "#42e2f4"
          message: Sukses melakukan deploy pada branch $CIRCLE_BRANCH
      - slack/status:
          fail_only: true

  test-prod:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install k6 loadimpact
          command: |
            sudo apt-get install apt-transport-https -y
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
            echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install k6
      - run:
          name: testing host
          command: k6 run --vus 10 --duration 10s prod_script.js
      - slack/notify:
          color: "#42e2f4"
          message: Sukses testing https://inv.member.co.id
      - slack/status:
          fail_only: true

workflows:
  version: 2.1
  workflow:
    jobs:
    - development:
        filters:
          branches:
            only: development
    - test-dev:
        requires:
          - development
    - staging:
        filters:
          branches:
            only: staging
    - test-stag:
        requires:
          - staging
    - production:
        filters:
          branches:
            only: master
    - test-prod:
        requires:
          - production

